routes/web.php
<?php

use App\Http\Controllers\Admin\IngredientController as AdminIngredientController;
use App\Http\Controllers\User\RecipeController as UserRecipeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/show/{recipe}', [App\Http\Controllers\HomeController::class, 'show'])->name('show');

Route::prefix('/user')->middleware(['auth', 'role:user'])->name('user.')->group(function () {
    Route::resource('recipe', UserRecipeController::class);
});

Route::prefix('/admin')->middleware(['auth', 'role:admin'])->name('admin.')->group(function () {
    Route::resource('ingredient', AdminIngredientController::class)->only('index');
});

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function recipes()
    {
        return $this->hasMany(Recipe::class, 'author_id');
    }
}

app/Http/Controllers/User/RecipeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Recipe;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $this->authorize('user', Recipe::class);

        $recipes = auth()->user()->recipes()->with(['dishType'])->orderBy('created_at', 'DESC')->paginate(5);

        return view('user.index', compact('recipes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $this->authorize('user', Recipe::class);

        $userId = auth()->user()->id;

        return view('user.create', compact('userId'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Recipe $recipe)
    {
        $this->authorize('author', $recipe);

        $ingredients = $recipe->ingredients()->get();

        return view('user.show', compact('recipe', 'ingredients'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Recipe $recipe)
    {

        $this->authorize('author', $recipe);

        $ingredients = $recipe->ingredients();

        $userId = auth()->user()->id;

        return view('user.edit')->with([
            'recipeId' => $recipe->id,
            'userId' => $userId,
            'oldIngredients' => $ingredients,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Recipe $recipe)
    {
        $this->authorize('author', $recipe);

        $recipe->delete();

        return redirect()->route('user.recipe.index');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <create-recipe-component user-id="{{ $userId }}"></create-recipe-component>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <edit-recipe-component user-id="{{ $userId }}" recipe-id="{{ $recipeId }}"></edit-recipe-component>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header h4 text-center">All my recipes</div>
                <div class="card-body">
                    <div class="container pt-2">

                        @if(!$recipes->isEmpty())

                            @foreach($recipes as $recipe)
                                <div class="col-md-12 border-bottom border-secondary border-2 mb-1 rounded-4">
                                    <div class="row ms-2 mt-1">
                                        <div class="col-md-3 pt-5">
                                            <img style="max-width: 100%; height: auto;"
                                                 src="{{ asset(('/storage/images/recipes/' . $recipe->image)) }}"
                                                 class="img-thumbnail" alt="{{ $recipe->name }}">
                                        </div>

                                        <div class="col-md-9">
                                            <h2>
                                                <a class="link-dark text-decoration-none"
                                                   href="{{ route('user.recipe.show', $recipe) }}">{{ $recipe->name }}</a>
                                            </h2>
                                            <ul class="list-unstyled text-small">
                                                <li>
                                                    {{--                                                        Author: <strong>{{ $recipe->author->name }}</strong>,--}}
                                                    Type: <strong>{{ $recipe->dishType->name }}</strong>
                                                </li>
                                            </ul>
                                            <p class="fs-5">{{ Str::limit($recipe->description, 200) }}</p>

                                            <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-2 me-2">
                                                <form method="post" class=""
                                                      action="{{ route('user.recipe.destroy', $recipe) }}">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="{{ route('user.recipe.edit', $recipe->id) }}"
                                                       class="btn btn-outline-primary">Edit</a>
                                                    <button type="submit"
                                                            class="btn btn-outline-danger ms-2 text-end"
                                                            onclick=" return confirm('Are you sure you wish to delete this recipe ?')">
                                                        Delete
                                                    </button>
                                                </form>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            @endforeach
                            <div class="justify-content-center">{{ $recipes->links() }}</div>
                    </div>
                    @else
                        <p class="mt-4">Make your first recipe</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header h4 text-center">Recipe for <b>{{ $recipe->name }}</b></div>

                <div class="card-body">
                    <div class="container pt-2">

                        <div class="col-md-12 border-start border-end border-secondary border-2 mb-3 rounded-4">
                            <div class="row ms-2 mt-2 pt-4">
                                <div class="col-md-3 pb-5">
                                    <img style="max-width: 100%; height: auto;"
                                         src="{{ asset(('/storage/images/recipes/' . $recipe->image)) }}"
                                         class="img-thumbnail" alt="{{ $recipe->name }}">
                                </div>

                                <div class="col-md-9">

                                    <ul class="list-unstyled text-small">
                                        <li>
                                            Author: <strong>{{ $recipe->author->name }}</strong>,
                                            <br>
                                            Type: <strong>{{ $recipe->dishType->name }}</strong>
                                        </li>
                                    </ul>
                                    <p class="fs-5">{{ $recipe->description }}</p>

                                    <ul class="list-group w-50">
                                        <li class="list-group-item"><strong>Ingredients list:</strong></li>

                                        @foreach($ingredients as $ingredient)
                                            <li class="list-group-item">- {{ $ingredient->name }}</li>
                                        @endforeach
                                    </ul>

                                    <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-2 me-2">
                                        <form method="post" class=""
                                              action="{{ route('user.recipe.destroy', $recipe) }}">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('user.recipe.edit', $recipe->id) }}"
                                               class="btn btn-outline-primary">Edit</a>
                                            <button type="submit"
                                                    class="btn btn-outline-danger ms-2 text-end"
                                                    onclick=" return confirm('Are you sure you wish to delete this recipe ?')">
                                                Delete
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection