routes/web.php
<?php

use App\Http\Controllers\Admin\IngredientController as AdminIngredientController;
use App\Http\Controllers\User\RecipeController as UserRecipeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/show/{recipe}', [App\Http\Controllers\HomeController::class, 'show'])->name('show');

Route::prefix('/user')->middleware(['auth', 'role:user'])->name('user.')->group(function () {
    Route::resource('recipe', UserRecipeController::class);
});

Route::prefix('/admin')->middleware(['auth', 'role:admin'])->name('admin.')->group(function () {
    Route::resource('ingredient', AdminIngredientController::class)->only('index');
});

Auth::routes();

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Recipes</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])

    <style>
        #app {
            display: flex;
            flex-direction: column;
            min-height: 85vh;
        }
        .container {
            flex: 1;
        }
        .center-middle {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin-top: 50vh; /* Half of the viewport height */
            transform: translateY(-50%);
        }
        /*.center-vertical {  !* Class for displaying cards vertically centered  *!*/
        /*    display: flex;*/
        /*    justify-content: center;*/
        /*    align-items: center;*/
        /*    height: 60vh;*/
        /*}*/
    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Recipes
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @include('layouts.navigation')

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @yield('content')
            </div>
        </main>
    </div>
</body>
    @include('layouts.footer')
</html>

resources/views/layouts/footer.blade.php
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{{ route('home') }}" class="nav-link px-2 text-body-secondary">Home</a></li>
            @can('user', \App\Models\Recipe::class)
                <li class="nav-item"><a href="{{ route('user.recipe.index') }}" class="nav-link ms-2 {{ request()->routeIs('user.recipe.index') ? 'active' : '' }}">My Recipes</a></li>
                <li class="nav-item"><a href="{{ route('user.recipe.create') }}" class="nav-link ms-2 {{ request()->routeIs('user.recipe.create') ? 'active' : '' }}">+ Write new recipe</a></li>
            @endcan

            @can('admin', \App\Models\Ingredient::class)
                <li class="nav-item"><a href="{{ route('admin.ingredient.index') }}" class="nav-link ms-2 {{ request()->routeIs('admin.ingredient.index') ? 'active' : '' }}">Ingredient</a></li>
            @endcan
        </ul>
        <p class="text-center text-body-secondary">© 2023 Recipes</p>
    </footer>
</div>

resources/views/layouts/navigation.blade.php
<ul class="navbar-nav me-auto">

    @can('user', \App\Models\Recipe::class)
        <li class="nav-item"><a href="{{ route('user.recipe.index') }}" class="nav-link ms-2 {{ request()->routeIs('user.recipe.index') ? 'active' : '' }}">My Recipes</a></li>
        <li class="nav-item"><a href="{{ route('user.recipe.create') }}" class="nav-link ms-2 {{ request()->routeIs('user.recipe.create') ? 'active' : '' }}">+ Write new recipe</a></li>
    @endcan

    @can('admin', \App\Models\Ingredient::class)
        <li class="nav-item"><a href="{{ route('admin.ingredient.index') }}" class="nav-link ms-2 {{ request()->routeIs('admin.ingredient.index') ? 'active' : '' }}">Ingredients</a></li>
    @endcan

</ul>